# my-nixos-config/.sops.yaml
# Defines who can decrypt which files

keys:
  - &new_key age1wlxnstlgxscd35jm9w09w7ys2k4n5ua0e4fgswef0nplfg09rsvsf86nux

creation_rules:
  # This rule applies to your main secrets file.
  # It allows decryption by your personal key AND the Age key of ANY of your servers.
  # This means any of your servers can decrypt the secrets relevant to them,
  # and you can decrypt and edit the file from your admin machine

  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *new_key

  - path_regex: secrets/nginx/nginx-selfsigned.key$
    key_groups:
      - age:
        - *new_key

