{config, ...}: {
  flake.nixosModules.books = 
    let
      baseurl = config.flake.meta.baseurl;
    in { pkgs, lib, config, ... }:
    let
      port = "6666";
    in {

      sops.secrets.grimmory = {
        sopsFile = ../../../../secrets/grimmory.env;
        format = "dotenv";
      };

      # Runtime
      virtualisation.podman = {
        enable = true;
        autoPrune.enable = true;
        dockerCompat = true;
      };

      # Enable container name DNS for all Podman networks.
      networking.firewall.interfaces = let
        matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
      in {
        "${matchAll}".allowedUDPPorts = [ 53 ];
      };

      virtualisation.oci-containers.backend = "podman";

      # Containers
      virtualisation.oci-containers.containers."grimmory" = {
        image = "docker.io/grimmory/grimmory:latest";
        environmentFiles = [ config.sops.secrets.grimmory.path ];
        environment = {
          "DATABASE_URL"      = "jdbc:mariadb://mariadb:3306/grimmory";
          "DATABASE_USERNAME" = "grimmory";
          "GROUP_ID"          = "5001";
          "SERVER_PORT"       = "${port}";
          "TZ"                = "Etc/UTC";
          "USER_ID"           = "5001";
          "SERVER_FORWARD_HEADERS_STRATEGY" = "framework";
        };

        volumes = [
          "/var/lib/grimmory/bookdrop:/bookdrop:rw"
          "/var/lib/grimmory/books:/books:rw"
          "/var/lib/grimmory/data:/app/data:rw"
          "/var/lib/grimmory/mariadb/config:/config:rw"
        ];

        ports = [
          "${port}:${port}/tcp"
        ];
        dependsOn = [
          "grimmory-mariadb"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=grimmory"
          "--network=grimmory_default"
        ];
      };

      systemd.tmpfiles.rules = [
        "d /var/lib/grimmory/mariadb/config 0755 5001 5001 -"
        "d /var/lib/grimmory/bookdrop        0755 5001 5001 -"
        "d /var/lib/grimmory/books           0755 5001 5001 -"
        "d /var/lib/grimmory/data            0755 5001 5001 -"
      ];

      systemd.services."podman-grimmory" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          EnvironmentFile = config.sops.secrets.grimmory.path;
        };
        unitConfig.Description = "Container grimmory generated by compose2nix.";
        after = [
          "podman-network-grimmory_default.service"
          "podman-grimmory-mariadb.service"
        ];
        requires = [
          "podman-network-grimmory_default.service"
          "podman-grimmory-mariadb.service"
        ];
        partOf = [
          "podman-compose-grimmory-root.target"
        ];
        wantedBy = [
          "podman-compose-grimmory-root.target"
        ];
      };

      virtualisation.oci-containers.containers."grimmory-mariadb" = {
        image = "lscr.io/linuxserver/mariadb:11.4.5";
          environmentFiles = [ config.sops.secrets.grimmory.path ];

        environment = {
          "MYSQL_DATABASE" = "grimmory";
          "MYSQL_USER"     = "grimmory";
          "PGID"           = "5001";
          "PUID"           = "5001";
          "TZ"             = "Etc/UTC";
        };
        volumes = [
          "/var/lib/grimmory/mariadb/config:/config:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--health-cmd=mariadb-admin ping -h localhost"
          "--health-interval=5s"
          "--health-retries=10"
          "--health-timeout=5s"
          "--network-alias=mariadb"
          "--network=grimmory_default"
        ];
      };

      systemd.services."podman-grimmory-mariadb" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
          EnvironmentFile = config.sops.secrets.grimmory.path;
        };
        unitConfig.Description = "Container grimmory-mariadb generated by compose2nix.";
        after = [
          "podman-network-grimmory_default.service"
        ];
        requires = [
          "podman-network-grimmory_default.service"
        ];
        partOf = [
          "podman-compose-grimmory-root.target"
        ];
        wantedBy = [
          "podman-compose-grimmory-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-grimmory_default" = {
        unitConfig.Description = "Network grimmory_default generated by compose2nix.";
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f grimmory_default";
        };
        script = ''
          podman network inspect grimmory_default || podman network create grimmory_default
        '';
        partOf = [ "podman-compose-grimmory-root.target" ];
        wantedBy = [ "podman-compose-grimmory-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-grimmory-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };

      services.nginx.virtualHosts."grimmory.${baseurl}" = {
        forceSSL = true;
        useACMEHost = "${baseurl}";
        locations."/" = {
          proxyPass = "http://127.0.0.1:${port}";
          proxyWebsockets = true;
          extraConfig = ''
            client_max_body_size 2G;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;
          '';
        };
      };
    };
}
